# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Filen
version: "0.0.17"
slug: filen
description: Filen WebDAV Server
url: "https://github.com/karteekiitg/hassio-addons/tree/main/filen"
arch:
  - aarch64
  - amd64
init: false
schema:
  FILEN_EMAIL: str
  FILEN_PASSWORD: str
  FILEN_2FA_CODE: "str?"
  WEBDAV_USERNAME: str
  WEBDAV_PASSWORD: str
options:
  FILEN_EMAIL: ""
  FILEN_PASSWORD: ""
  FILEN_2FA_CODE: ""
  WEBDAV_USERNAME: "ha"
  WEBDAV_PASSWORD: "ha"
ports:
  443/tcp: 22288
map:
  - type: addon_config
    read_only: False
  - type: data
    read_only: False
